
openweathermap:
  api:
    key: KEY
    host: 37.139.1.159 #api.openweathermap.org

spring:
  resources:
    gtfsFile: classpath:data/consolidated_gtfs.json
    queryDataFile: classpath:data/query_data.json
    roadProcessedDataFile: classpath:data/road_map.json