
openweathermap:
  api:
    key: KEY
    host: 37.139.1.159 #api.openweathermap.org

postgresql:
  api:
    host: 140.238.228.234
    port: 8086
    dbName: postgres
    dbUserName: pastav
    dbPassword: ase123pastav

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST_NAME:${postgresql.api.host}}:${POSTGRES_PORT:${postgresql.api.port}}/${POSTGRES_DB:${postgresql.api.dbName}}
    username: ${POSTGRES_USER:${postgresql.api.dbUserName}}
    password: ${POSTGRES_PASSWORD:${postgresql.api.dbPassword}}
    driver-class-name: org.postgresql.Driver


  resources:
    gtfsFile: classpath:data/consolidated_gtfs.json
    queryDataFile: classpath:data/query_data.json
    roadProcessedDataFile: classpath:data/road_map.json